Training with a single process on 1 GPUs.
Downloading: "https://storage.googleapis.com/vit_models/augreg/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0--imagenet2012-steps_20k-lr_0.01-res_224.npz" to /home/zc1995/.cache/torch/hub/checkpoints/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0--imagenet2012-steps_20k-lr_0.01-res_224.npz
Model vit_base_patch16_224 created, param count: 85407747
Data processing configuration for current model + dataset:
	input_size: (1, 224, 224)
	interpolation: bicubic
	mean: (0.5128,)
	std: (0.2236,)
	crop_pct: 0.875
Using native Torch AMP. Training in mixed precision.
Scheduled epochs: 210
Traceback (most recent call last):
  File "train.py", line 824, in <module>
    main()
  File "train.py", line 612, in main
    train_metrics = train_one_epoch(
  File "train.py", line 683, in train_one_epoch
    output = model(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 363, in forward
    x = self.forward_features(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 355, in forward_features
    x = self.blocks(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 230, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x)))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/layers/mlp.py", line 27, in forward
    x = self.act(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 669, in forward
    return F.gelu(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1555, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: CUDA out of memory. Tried to allocate 444.00 MiB (GPU 0; 8.00 GiB total capacity; 5.70 GiB already allocated; 0 bytes free; 5.79 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "train.py", line 824, in <module>
    main()
  File "train.py", line 612, in main
    train_metrics = train_one_epoch(
  File "train.py", line 683, in train_one_epoch
    output = model(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 363, in forward
    x = self.forward_features(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 355, in forward_features
    x = self.blocks(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/vision_transformer.py", line 230, in forward
    x = x + self.drop_path(self.mlp(self.norm2(x)))
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/timm/models/layers/mlp.py", line 27, in forward
    x = self.act(x)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 669, in forward
    return F.gelu(input)
  File "/home/zc1995/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 1555, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: CUDA out of memory. Tried to allocate 444.00 MiB (GPU 0; 8.00 GiB total capacity; 5.70 GiB already allocated; 0 bytes free; 5.79 GiB reserved in total by PyTorch)